# Generated by Django 2.1.4 on 2019-01-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reRepeat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='skip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
