# Generated by Django 2.1.4 on 2019-01-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reRepeat', '0003_auto_20190116_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_text',
            field=models.TextField(max_length=10000),
        ),
    ]
