# Generated by Django 2.1.4 on 2019-01-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reRepeat', '0004_auto_20190116_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_text',
            field=models.TextField(max_length=1000),
        ),
    ]
