# Generated by Django 2.1.4 on 2019-01-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reRepeat', '0006_auto_20190125_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_text',
            field=models.TextField(max_length=2000, verbose_name='Answer'),
        ),
    ]
